#!/usr/bin/env fish

if test -f ~/.config/dm-scripts/config.fish
    source ~/.config/dm-scripts/config.fish
else
   set _dmenu "dmenu"
end

set _dmscriptdir $HOME/.local/scripts/dm-scripts/ 
set _options (ls $_dmscriptdir)

set choice (printf '%s\n' $_options | \
    sort | \
    awk '{print NR": "$0}' | \
    $_dmenu -i -l 10 -p "DM-Scripts") || exit 1

set _chosen (echo "$choice" | awk -F ': ' '{print $NF}')

if test -n $_chosen 
    $_dmscriptdir$_chosen &
else
    exit 1
end

disown
exit 0
