#!/usr/bin/env fish

if test -f ~/.config/dm-scripts/config.fish
    source ~/.config/dm-scripts/config.fish
else
    set _dmenu "dmenu"
    set _dmbrowser "xdg-open"
end

# ENGINE - ENGINEURL
set _options \
    "DuckDuckGo - https://duckduckgo.com/?ia=web&origin=funnel_home_searchresults&t=ftsa&q=" \
    "Brave - https://search.brave.com/search?q=" \
    "Google - https://www.google.com/search?q=" \
    "SearxNG - https://searx.tiekoetter.com/search?q=" \
    "Youtube - https://www.youtube.com/results?search_query=" \
    "Wikipedia - https://en.wikipedia.org/w/index.php?search=" \
    "ArchWiki - https://wiki.archlinux.org/index.php?search=" \
    "AUR - https://aur.archlinux.org/packages?O=0&K=" \
    "Startpage - https://www.startpage.com/sp/search?query="

set _enginelist (for _i in $_options; echo $_i; end | sort | \
    awk '{print NR": "$0}' | \
    $_dmenu -i -l 10 -p 'Choose your search engine' || exit 1 )

set _engineurl (echo "$_enginelist" | awk '{print $NF}') 
set _engine (echo "$_enginelist" | awk '{print $2}')
set _query (echo "" | $_dmenu -i -p "Search $_engine") || exit 1

$_dmbrowser "$_engineurl$_query" & 

disown
exit 0
